spring.application.name=literalura
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=Contra123.

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

